### ISSUE TITLE
Unhandled Exception: MissingPluginException on AppleSignIn.performRequests

### ISSUE THREAD

**Issue by Style87** [tomgilder/flutter_sign_in_with_apple#10]
I've followed the instructions and copied the button and handler code from the example into my app. When the code executes
```
final AuthorizationResult result = await AppleSignIn.performRequests([
  AppleIdRequest(requestedScopes: [Scope.email, Scope.fullName])
]);
```
I get the exception below.
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method performRequests on channel dev.gilder.tom/apple_sign_in)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      AppleSignIn.performRequests (package:apple_sign_in/apple_sign_in.dart:42:41)
<asynchronous suspension>
#2      _LoginScreenState.doLoginWithApple (package:ping/screens/loginScreen/Login.screen.dart:306:58)
<asynchronous suspension>
#3      _AppleSignInButtonState.build.<anonymous closure> (package:apple_sign_in/apple_sign_in_button.dart:54:17)
#4      TapGestureRecognizer._checkUp.<anonymous closure> (package:flutter/src/gestures/tap.dart:363:49)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:363:11)
#7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
#10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
#11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
#12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#16     _rootRunUnary (dart:async/zone.dart:1136:13)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#19     _invoke1 (dart:ui/hooks.dart:263:10)
#20     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
```
Have I missed something obvious or is this an issue with the plugin?

**Comment by GeoffGodwin** [comment]
I'm receiving the same error. Before I'd seen this error when Flutter needed a fresh run after adding a new plugin (as opposed to hot reload) but even after flutter cleaning I seem to be getting this error.

**Comment by OliverNarramore** [comment]
I'm also getting this error

**Comment by OliverNarramore** [comment]
Prior to calling "final AuthorizationResult result = await AppleSignIn.performRequests([
  AppleIdRequest(requestedScopes: [Scope.email, Scope.fullName])
]);"

Check if the apple sign is available, i found this error occurred when sign in wasn't actually available.

**Comment by zariweyo** [comment]
When is apple sign available or not?

**Comment by Style87** [comment]
Apple sign was not available. Checking availability did the trick.

**Comment by jlcool** [comment]
@Style87 What should I do? How to checking availability did the trick.

**Comment by mhlulani** [comment]
I think I understand what @Style87 is saying, it appears that not every device supports AppleSignIn so what you will have to do is to check if it's supported on the current device using the following:
```dart
if (!await AppleSignIn.isAvailable()) {
    return null; //Break from the program
}

final AuthorizationResult result = await AppleSignIn.performRequests([
  AppleIdRequest(requestedScopes: [Scope.email, Scope.fullName])
]);
```
Better yet toggle the _Sign in with Apple_ button from your app using `isAvailable()` so that users cannot click on it.

"To sign into an app or website that offers Sign in with Apple, you need: 

- An Apple ID that uses two-factor authentication.
- To be signed in to iCloud with this Apple ID on your Apple device.

Sign in with Apple is available with participating apps on Apple devices with the latest software—iOS 13 or later, iPadOS 13 or later, watchOS 6 or later, macOS Catalina 10.15 or later, and tvOS 13 or later—and with participating websites in Safari. You can also use Sign in with Apple with other web browsers and on other platforms, like Android or Windows."

https://support.apple.com/en-us/HT210318

**Comment by yourshinsuke** [comment]
It always `isAvailable` it false...

**Comment by mhlulani** [comment]
> It always `isAvailable` it false...

`isAvailable` is NOT a state of the App but the state of the platform, it's simply checking if that platform supports the Apple sign in

Hope this helps

**Comment by yourshinsuke** [comment]
@mhlulani Thank you. my iPhone is iOS12.
it only support iOS13 or more?

**Comment by mhlulani** [comment]
I think it's important to read all the responses in their entirety,  your question has already been answered there is even a link to Apple explaining this

**Comment by Style87** [comment]
Apologies for not responding sooner but @mhlulani is 100% correct. Their code snippet is exactly what I have in my project and that is the solution to the original issue.

**Comment by happy-cat-coder** [comment]
So... If i run my app on android I can't log with Apple? And if I can, how should I write my code to work?

**Comment by mhlulani** [comment]
@bestkid1234 , that information is on the plugin's page https://pub.dev/packages/sign_in_with_apple/example.

You'll need to implement the `webAuthenticationOptions` section
