### ISSUE TITLE
Invalid Token received

### ISSUE THREAD

**Issue by ssbaval** [tomgilder/flutter_sign_in_with_apple#12]
Hi - I have successfully authenticated against Apple and get an AuthorizationStatus.authorized code.

I now want to use the credentials to sign in with the apple ID with Firebase, i.e I have this enabled in Firebase console : 

![image](https://user-images.githubusercontent.com/56350563/69759425-03ff1900-115a-11ea-929b-3e9c1c7c954c.png)

To do this I use the identifyToken returned in the result but when I try and use FirebaseAuth.signInWithCustomToken(appleToken) I get : 

![image](https://user-images.githubusercontent.com/56350563/69759377-d9ad5b80-1159-11ea-9327-a8d3ffbce42c.png)

is there something I'm missing here ?

**Comment by dacxjo** [comment]
Im stuck here too, but a little further .

Im trying to do the exact same thing, sign in with apple with firebase, what i do was a cloud function on firebase that get the uuid from the apple sign in and turn it into a custom token to use it later with signInWithCustomToken, here is the cloud function that i have:
```

const admin = require("firebase-admin");
const functions = require("firebase-functions");
admin.initializeApp();
exports.appleToken = functions.https.onCall(async (data, context) => {
  let uuid = data.uuid;
  let token = "";

  if (uuid != "") {
    await admin
      .auth()
      .createCustomToken(uuid)
      .then(tkn => {
        token = tkn;
        console.log(tkn);
      });

    return {
      token: token
    };
  } else {
    return null;
  }
});
```

Then using the[ cloud_function](https://pub.dev/packages/cloud_functions) package from flutter make a call to execute this function when apple Sign In Status is authorized , and then call the firebase_auth method signInWithCustomToken:

```
await callable.call(<String, dynamic>{
            'uuid': result.credential.user,
          })
          .then((HttpsCallableResult res) async{
            print(res.data['token']);
           await _auth.signInWithCustomToken(token:res.data['token'])
           .then((authRes){
             print(authRes);
           });
          })
          .catchError((err){
            print(err);
          });
        
        } on CloudFunctionsException catch (e) {
          print(e.message);
          print(e.details);
        } 


```

And this i what i get , an empty auth credential . I dont know what else do with this.

[Result](https://imgur.com/ireKu5i)

**Comment by therealjohnsummer** [comment]
@dacxjo  This is expected behavior within firebase using custom Auth. You should update the email **ONLY** after you get back a valid token on the client. Then you will see the email field in the firebase console.

Also - did you configure apple sign in properly on developer.apple ?   What specifically did you do and also did you enable the correct capability in xcode ?

**Comment by tomgilder** [comment]
Closing as per comment above, expected behaviour and not to do with this plugin
