### ISSUE TITLE
After the first sign in , email and fullName becomes null

### ISSUE THREAD

**Issue by dacxjo** [tomgilder/flutter_sign_in_with_apple#13]
Im trying to implement the apple sign in to deploy my app to the App Store but we found that after the first sign in , the object result.credential.email and fullName returns null, also the authorized scopes is always empy??

Dont know how to proceed after this , any help is welcome

[First Authorization](https://imgur.com/QoiqwT9)
[Next Authorizations](https://imgur.com/2pc3Kry)

**Comment by dacxjo** [comment]
I just want to know how to retrieve email and password when the account is already authorized

**Comment by lgArlequin** [comment]
I have the same question.

**Comment by lgArlequin** [comment]
I just found that you can get the email if you parse the identityToken token that the credentials return, if that works for you at least.

**Comment by dacxjo** [comment]
@lgArlequin thanks im going to try that!

**Comment by minhtruong315** [comment]
same issue. I tried on simulator, it's working well, but it has issue when run app on real device. anyone has solutions?

**Comment by dacxjo** [comment]
@lgArlequin  you were right , you can get the email from the token i have to use some snippets from google to parse the JWT.

now i have : 

  ```
var appleUser = parseJwt(utf8.decode(result.credential.identityToken));

        print(appleUser['email']);
        try {
          await callable.call(<String, dynamic>{
            'uuid': result.credential.user,
            'name': result.credential.fullName.givenName,
            'email': result.credential.email == null
                ? appleUser['email']
                : result.credential.email
          }).then((HttpsCallableResult res) async {
            await _auth
                .signInWithCustomToken(token: res.data['token'])
                .then((authRes) {
              print(authRes);
            });
            Navigator.of(context, rootNavigator: true).pop();
            notifyListeners();
          }).catchError((err) {
            print(err);
          });
        } on CloudFunctionsException catch (e) {
          print(e.message);
          print(e.details);
        }
```
where parseJwt function come from [here](https://gist.github.com/hjJunior/2fd180c703919fc4bca8337ac3c56268)

the callable then call a cloud function to get the custom token and create the user if not exist or get it if exist .

**Comment by vinwonghk** [comment]
this is an expected behavior, after first time sign in, Apple will not pass user's name and email again.

please check here:
https://stackoverflow.com/questions/57714339/sign-in-with-apple-different-behaviour-simulator-vs-iphone
https://stackoverflow.com/questions/57545635/cannot-get-name-email-with-sign-in-with-apple-on-real-device

**Comment by tomgilder** [comment]
Yep, closing - this is the expected behaviour, see https://forums.developer.apple.com/thread/121496
