### ISSUE TITLE
flutter_apple_sign_in parse error in xcode

### ISSUE THREAD

**Issue by Mallika-Tung** [tomgilder/flutter_sign_in_with_apple#14]
I am facing these type of parse issue in xcode to running the apple_sign_in

![Screenshot 2019-11-29 at 7 23 35  PM](https://user-images.githubusercontent.com/51913248/69873789-4aca4b80-12df-11ea-901c-5e26883038e1.png)

!

**Comment by fernandongana** [comment]
I am getting the same error, do you solved this issue?

**Comment by Mallika-Tung** [comment]
No i am not  able to solve.This plugin code has lots of compiler ,parser issue
    On Monday, December 2, 2019, 8:01:44 PM GMT+5:30, Fernando Constantino Ngana <notifications@github.com> wrote:  
 
 
I am getting the same error, do you solved this issue?

**Comment by ShubhamSingla125** [comment]
I am also getting the same error. Anybody have resolved this issue?

**Comment by tomgilder** [comment]
Can you post reproduction steps as to how you're opening the project in Xcode to get these errors?

The project is compiling fine for me.

**Comment by Mallika-Tung** [comment]
i am opening xcworkspace in xcode 10.2 and os Mojave.

**Comment by GerlanStanley** [comment]
I had the same problem, I solved updating xcode

**Comment by tomgilder** [comment]
Yes, it requires Xcode 11. Have added an FAQ to the readme.
