### ISSUE TITLE
Stuck after password input

### ISSUE THREAD

**Issue by vasilich6107** [tomgilder/flutter_sign_in_with_apple#17]
Hi. Thanks for the plugin. 
I have an issues including it into my project.
I tried even on newly created flutter project but it does not work.

Steps to reproduce:

1. Create new flutter project with android studio
2. Copy/paste the `pubspec.yaml` from `example` into new project
3. Copy/paste the `lib` contents from `example` into new project
4. Launch the new project in the debugger
5. Try to login with apple id. The whole process runs smoothly
6. On the last step when you enter the password the spinner appears in the password field and then nothing happens. No errors in console. No errors in XCode. Just silence.
7. This could be fixed with copy/pasting the `ios` folder from `example` project into newly created. But this looks pretty hacky.

Maybe I'm missing something in setup process?

**Comment by vasilich6107** [comment]
It seems that Apple sign in capability requires a valid developer account(

**Comment by NedWilbur** [comment]
@vasilich6107 This was my issue.. I forgot to sign in to my new dev account in xcode, thank you. Adding reference image for other users who may also encounter this.
![image](https://user-images.githubusercontent.com/19377058/75213313-b34a8c80-5757-11ea-9226-f43be40e14e2.png)

**Comment by devrajraut** [comment]
@vasilich6107 Im facing the same issue. I have a Paid developer account and I have also signing into the Teams on Xcode. But I can't seem to go past the Password screen. The spinner does its thing but nothing after that. No error in console. No other warning. What could be the issue? I'm new to Flutter. Thanks.

**Comment by superwei629** [comment]
Im facing the same issue

**Comment by hardikvij195** [comment]
im also facing this issue...please help

**Comment by Tobi696** [comment]
Still facing the same issue on a Paid Personal developer account.

**Comment by harshkumarkhatri24** [comment]
Me too, still it is same

**Comment by JoorgeFerrari** [comment]
Following
