### ISSUE TITLE
data received null flutter_apple_sign_in  

### ISSUE THREAD

**Issue by muhmmedAbdelkhalik** [tomgilder/flutter_sign_in_with_apple#18]
![](https://user-images.githubusercontent.com/55117049/70751305-c0e79d00-1d38-11ea-8607-a0db3edf29e4.png)

**Comment by ramiechaarani** [comment]
@muhmmedAbdelkhalik did you ever figure out what was wrong?

**Comment by muhmmedAbdelkhalik** [comment]
@ramiechaarani  until now noo

**Comment by ramiechaarani** [comment]
@muhmmedAbdelkhalik the issue has to do with apple's method of handlign apple sign in. It will only ever pass the information over on the very first register/login. Meaning you have to delete teh account and go here: https://appleid.apple.com/account/manage and click on "Manage" under APPS & WEBSITES USING APPLE ID. Once you clear it it should work again. This means you need to save all of your info on your upon initial registration. Good luck!

**Comment by muhmmedAbdelkhalik** [comment]
@ramiechaarani delete them and same issue 😕

**Comment by tomgilder** [comment]
This is how Sign In with Apple functions. After the first login the details are null. See confirmation from an Apple engineer: https://forums.developer.apple.com/thread/121496
