### ISSUE TITLE
Apple rejection

### ISSUE THREAD

**Issue by paddykily** [tomgilder/flutter_sign_in_with_apple#19]
Apple rejected our app for the following reason. They won't explain what the exact problem is.

> We noticed an issue in your app that contributes to a lower quality user experience than Apple users expect:
> 
> - Your app uses Sign in with Apple as a login option but does not use Sign in with Apple button design, branding and/or user interface elements appropriately as described in the Sign in With Apple Human Interface Guidelines.
> 
> Next Steps
> 
> To resolve this issue, please revise your app to address all instances of this type of issue.
> 
> Resources
> 
> For information on improving and enhancing your app:
> 
> - Watch the video The Ingredients of Great Apps to understand the basics of great apps.
> - Watch the video iPhone and iPad User Interface Design for practical design tips.
> - Watch iOS Development Videos to learn about programming and design tips.
> - Review the iOS Human Interface Guidelines and ensure that your app's interface and design adhere to these guidelines.
> 
> Please see attached screenshot for details.

<img width="599" alt="Screenshot 2019-12-20 at 12 44 32 AM" src="https://user-images.githubusercontent.com/3038123/71220842-028cc080-22c2-11ea-879d-b522d8234160.png">

**Comment by edeuss** [comment]
They are talking about the button that opens that popup. @paddykily

**Comment by paddykily** [comment]
@EliasDeuss They would've sent a screenshot showing the button if that was the issue. The issue is with the popup I think. Maybe they couldn't get past it - something I couldn't reproduce after multiple trials.

**Comment by edeuss** [comment]
@paddykily Oh huh maybe it's because the keyboard is also open? I have no idea past the keyboard.

**Comment by Ahmadre** [comment]
Try this: https://pub.dev/packages/flutter_auth_buttons

The buttons there are following the guidelines like mentioned here: https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/

Important note: You have to be aware of the **contrast** between button and background.

Also note this:
**"Prominently display a Sign in with Apple button. Make a Sign in with Apple button no smaller than other sign-in buttons, and avoid making people scroll to see the button."**

For the keyboard and popup: you can unfocus your actual textfield focus by:

```dart
    focusNodeOfTextfield.unfocus();
```

just call that method before the sign in process begins to dismiss the keyboard.

That hides the actual keyboard by dismissing the focus on the textfield

**Comment by tomgilder** [comment]
Did you get past this? Did Apple clarify what the issue was?

**Comment by paddykily** [comment]
Has to do with the keyboard.
