### ISSUE TITLE
How does one log out of Apple Sign In?

### ISSUE THREAD

**Issue by davydany** [tomgilder/flutter_sign_in_with_apple#20]
I was able to use this medium post (https://medium.com/@karlwhiteprivate/flutter-firebase-sign-in-with-apple-c99967df142f) to login my user. How do I log out a user who has signed in with Apple Sign in?

**Comment by JTorrus** [comment]
I am facing the same problem. I was looking for a `signOut()` method like with other social providers. A bit of guidance with this issue would be appreciated. Thanks!

**Comment by tomgilder** [comment]
Sign In with Apple doesn't have a sign out function; this is up to you to handle in your app by removing the credentials you've stored.

If users want to delink their Apple account from your app they can go to  https://appleid.apple.com/account/manage -> "Apps & Websites Using Apple ID" -> "Manage"

**Comment by davydany** [comment]
@JTorrus I found that this works well for me:

```dart
FirebaseAuth _auth = FirebaseAuth.instance;

signOutUser() async {
    await _auth.signOut();
}
```
