### ISSUE TITLE
Failed to build in Xcode (Making Archive)

### ISSUE THREAD

**Issue by johnsonyick** [tomgilder/flutter_sign_in_with_apple#22]
I have successfully built with the command `flutter  build ios --release` with the screen below.
![image](https://user-images.githubusercontent.com/48547622/71504944-5137ed00-28b6-11ea-8765-4d624947428c.png)

however it's getting failed while making general ios device ipa by Xcode> Product > Archive
![image](https://user-images.githubusercontent.com/48547622/71504910-35cce200-28b6-11ea-8ba2-438d6f52faf6.png)

**Comment by tomgilder** [comment]
What version of Xcode are you using? It must built with Xcode 11 with the iOS 13 SDK.

**Comment by johnsonyick** [comment]
Sorry I have made a mistake, it's now fixed!
