### ISSUE TITLE
Authorization failed: Error Domain=AKAuthenticationError Code=-7026 "(null)" UserInfo=

### ISSUE THREAD

**Issue by viniciuspaulo** [tomgilder/flutter_sign_in_with_apple#23]
Error trying ->  final AuthorizationResult result = await AppleSignIn.performRequests([
    AppleIdRequest(requestedScopes: [Scope.email, Scope.fullName])
  ]);

2019-12-30 18:40:46.796195-0300 Runner[89962:599664] [core] Authorization failed: Error Domain=AKAuthenticationError Code=-7026 "(null)" UserInfo={AKClientBundleID=br.com.enterprise.vbbritodepaulo}
2019-12-30 18:40:46.826946-0300 Runner[89962:599596] flutter: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)

**Comment by tomgilder** [comment]
Have you enabled the Sign in with Apple capability? https://help.apple.com/xcode/mac/11.0/#/dev50571b902

**Comment by samsonsunny** [comment]
You have to enable sign in with apple capability both in your developer console as well in Xcode.

**Comment by pk359** [comment]
> Have you enabled the Sign in with Apple capability? https://help.apple.com/xcode/mac/11.0/#/dev50571b902

coming from capacitor. I was struggling a lot on this issues. Guess we all share the share problem on apple login. Man, your suggestions saved my week.

**Comment by jerald-jacob** [comment]
Authorization failed: Error Domain=AKAuthenticationError Code=-7026 "(null)" UserInfo={AKClientBundleID=my bundile id}
 I have the same issue.  enabled the sign in with apple capability both developer console as well in Xcode, but the error still remains.

**Comment by HoaDucHung96** [comment]
You have sign in with apple in file .entitlements

**Comment by AbdullaevTimur** [comment]
Have the save issue. I have **"sign in with apple"** in file .**entitlements**. Also then in my log i catch error `[com.apple.authkit:core] AuthKit password-reset-token token is missing! Account: xxx@**asas.app (D2828BEB-9F6B-406C-8A68-2A67ABA9315D). Credential: <ACAccountCredential: 0x7fcfad15fe40>.`, and only then `[com.apple.authkit:core] Failed to check in with IDMS! Error: Error Domain=AKAuthenticationError Code=-7026 "(null)"`. You can reproduce it if you run command **"log stream"** in your **"terminal"**(CLI) and lunch Xcode device simulator or debug your app on real device with USB connection.
