### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by hanneskuettner** [tomgilder/flutter_sign_in_with_apple#3]
Thanks for creating this package!

Could you be so kind and add a proper license to this project so we are in the clear when using it in our projects?

**Comment by tomgilder** [comment]
You're welcome; done - MIT licensed

**Comment by awhitford** [comment]
Apps that use this plugin  (version 0.1.0) as well as the [showLicensePage](https://api.flutter.dev/flutter/material/showLicensePage.html) (which is built into the [AboutDialog](https://api.flutter.dev/flutter/material/AboutDialog-class.html)), show a "TODO: Add your license here."

[It appears that we need a release cut with the license file included.](https://api.flutter.dev/flutter/foundation/LicenseRegistry-class.html)
