### ISSUE TITLE
Cannot build app with fastlane and xcode

### ISSUE THREAD

**Issue by A-Hama** [tomgilder/flutter_sign_in_with_apple#31]
This issue is same as #22, but bit different.

This is SDK version and Xcode version
```
iPhoneOS13.2.sdk - iOS 13.2 (iphoneos13.2)
 
Xcode 11.2.1
```

<img width="1228" alt="スクリーンショット 2020-02-11 17 13 05" src="https://user-images.githubusercontent.com/22091947/74220141-21239c80-4cf2-11ea-9f6d-6d49aedb2644.png">

Please help me!!!

**Comment by A-Hama** [comment]
I already found solution about this.
This was caused by the Scheme settings in Xcode.

**Comment by joknjokn** [comment]
What did you change? We have the same problem.

**Comment by A-Hama** [comment]
@joknjokn 
I checked Scheme settings firstly.
Then, I found that Debug is set to "build configuration" in stg and prod.
I changed them to xxx-stg and yyy-prod.
That works to me.

<img width="276" alt="スクリーンショット 2020-02-13 21 20 22" src="https://user-images.githubusercontent.com/22091947/74435193-3e4d9c00-4ea7-11ea-800f-ab238fd9ea16.png">
↑
Select "Edit Scheme"


<img width="883" alt="スクリーンショット 2020-02-13 21 20 39" src="https://user-images.githubusercontent.com/22091947/74435201-43aae680-4ea7-11ea-8c70-d17f75905c81.png">
↑
Change "Build configuration"

**Comment by joknjokn** [comment]
It didn't solve our problem, but thank you for the reply!
