### ISSUE TITLE
 apple_sign_in s failed after migrating project to swift

### ISSUE THREAD

**Issue by HaithamSheshtawy** [tomgilder/flutter_sign_in_with_apple#4]
After migrating project to swift the apple_sign_in stoped working and gives the error below:
Sign in failed: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)

**Comment by tomgilder** [comment]
Can you post reproduction steps for this please?

After migrating which project? Your own or this one?

**Comment by AminPlusPlus** [comment]
@tomgilder 
I'm getting same error but without any migration :( 
debugging on ios physical device.

flutter: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)

**Comment by AminPlusPlus** [comment]
@HaithamSheshtawy @tomgilder 
The issue is you have to add **Sign In with Apple** capabilities in Xcode debug/release if needed profile.
