### ISSUE TITLE
can't get the clickable action on the sign in with apple button in production release build.

### ISSUE THREAD

**Issue by jerald-jacob** [tomgilder/flutter_sign_in_with_apple#46]
Hi,
This was the problem,
I was created an app with the help of flutter_apple_sign_in by integrating the apple sign in. all the debug builds are working properly. and the last time I was build the production release and trying to click the button, I can't get the clickable action on the sign in with apple button.
plz hlp me

**Comment by jerald-jacob** [comment]
Updated the Provisioning profile with manually managing sign in.

**Comment by Livinglist** [comment]
Hi, I’m having the same problem. What did you do to resolve?

**Comment by sathyarajshetigar** [comment]
@jerald-jacob Hi can you please share with us how you managed to fix it?
Even I have the same issue. Works all fine in development build and fails in production build in test flight

**Comment by jerald-jacob** [comment]
Hi, Updated the Provisioning profile with manually managing sign in.[]()![images (7).jpeg](https://user-images.githubusercontent.com/25875900/90924233-b5db2580-e40c-11ea-9fa1-df3b1d042b0e.jpeg)
