### ISSUE TITLE
Missing Implementation

### ISSUE THREAD

**Issue by rawnly** [tomgilder/flutter_sign_in_with_apple#47]
When I try to login on Simulator this happens:

```log
MissingPluginException(No implementation found for method isAvailable on channel dev.gilder.tom/apple_sign_in)
```

**Comment by shinriyo** [comment]
Me too.
@Rawnly Did yo resolve?
I thought what is `gilder.tom`and tom is typo. because, it might be `com`.
Finally it is author's name lol
