### ISSUE TITLE
when use hide my email get appleIdCredential.email email null

### ISSUE THREAD

**Issue by egphp** [tomgilder/flutter_sign_in_with_apple#48]
when use hide my email get appleIdCredential.email email null

appleIdCredential.email working good 

but when choose hide i can't get hide one to forward to !!!!!

**Comment by egphp** [comment]
ok thanks i understand now after read it 


On signing in again, all the properties are null. You need to store them the first time you login.

For testing purposes you can revoke the credentials to sign in again:

Sign in to https://appleid.apple.com/account/manage
Go to "Apps & Websites Using Apple ID" and click "Manage"
Select your app
Click "Stop Using Apple ID"

**Comment by spookymodem** [comment]
@egphp Thank you for posting this!  I've been bashing my head on my desk for days, struggling to figure out why I am getting back a null email address.  After reading your comments here, I realize I had the same problem as you.  Thanks again!
