### ISSUE TITLE
can I use my own UX buton

### ISSUE THREAD

**Issue by premtemp1** [tomgilder/flutter_sign_in_with_apple#51]
Hello,
 I know this plugin provide an apple sign in button but the icon is too small and apple reject my build.. Can I create my own button and use this plugin?..

Also, I see another plugin is available for apple login with flutter. Is this plugin still maintain and  is this one better.

**Comment by shinriyo** [comment]
better than https://pub.dev/packages/sign_in_with_apple?

**Comment by premtemp1** [comment]
yep.. Just want to know  the differences between the two packages and which one should i use.
