### ISSUE TITLE
Is it required to use the native Apple button?

### ISSUE THREAD

**Issue by long1eu** [tomgilder/flutter_sign_in_with_apple#6]

**Comment by edeuss** [comment]
Yes it is. It is required by Apple. @long1eu

**Comment by long1eu** [comment]
Can you provide any source for this?

**Comment by long1eu** [comment]
@EliasDeuss can you please provide some source for your statement?

**Comment by edeuss** [comment]
@long1eu Just looked on the developer page and they let you do more than I thought but you can look at apples site here: https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/

**Comment by long1eu** [comment]
So in other works you don't need the Apple button. Am I right?

**Comment by edeuss** [comment]
I think you don't but you still have to follow there guidelines on that for color font and sizing. @long1eu

**Comment by long1eu** [comment]
@EliasDeuss have to?

**Comment by edeuss** [comment]
Yes it says on the guidelines @long1eu

**Comment by tomgilder** [comment]
Not sure if Apple are actually rejecting apps for not using the official button design, it doesn't actually specify it in the review guidelines - https://developer.apple.com/app-store/review/guidelines/#4.8

The UI guidelines only say "best to use the familiar buttons", so you might be fine with a custom design. Try it and see, and let us know! 😄

**Comment by long1eu** [comment]
The point of my question was related to the fact that you use PlatformView. And this enables some overhead on the iOS flutter engine. 

So my question is not related to the design, but rather as the title mentions the use of native Apple button.

**Comment by tomgilder** [comment]
`AppleSignInButton` is a Flutter recreation of the button - https://github.com/tomgilder/flutter_apple_sign_in/blob/master/lib/apple_sign_in_button.dart

Although it's only in English, really need to work out a way to do localisations on it.

**Comment by long1eu** [comment]
https://github.com/tomgilder/flutter_apple_sign_in/blob/ff60da707f9033140e6fd352f17c16f319a82e9f/example/ios/Runner/Info.plist#L44

https://github.com/tomgilder/flutter_apple_sign_in/blob/d8a6506f5f49dc2a60157f310f7483bea48e66a2/ios/Classes/AppleIDButtonFactory.h

**Comment by tomgilder** [comment]
The example requires platform views to be enabled because there's a test page which compares the native button and the Flutter button to check the design. It's not required to use the package.
